spring:
  application:
    name: main

  profiles:
    active: store1, store2

  datasource:
    url: "jdbc:mysql://localhost:3306/cars?createDatabaseIfNotExist=true"
    username: "root"
    password: "8520456Ss@"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.pssfk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: car-service

